[package]
name = "kvs"
version = "0.1.0"
authors = ["Aiwa Misaki <zyxwhisper@gmail.com>"]
description = "A key-value store"
edition = "2018"

[dependencies]
predicates = "3.1.3"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"